

trueDict = {}
predDict = {}

trueDict["CL1"] = ['Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger'] 
predDict["CL1"] =['Neutral', 'Neutral', 'Neutral', 'Bored', 'Neutral', 'Neutral', 'Sad', 'Neutral', 'Sad', 'Sad', 'Neutral', 'Sad', 'Neutral', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Bored', 'Neutral', 'Neutral', 'Bored', 'Sad', 'Bored', 'Sad', 'Bored', 'Bored', 'Sad', 'Happy', 'Sad', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Sad', 'HotAnger', 'Happy', 'Happy', 'Happy', 'HotAnger', 'Happy', 'HotAnger', 'HotAnger', 'HotAnger', 'Happy', 'Happy']

trueDict["CC1"] = ['Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger']
predDict["CC1"] =['Bored', 'Sad', 'Bored', 'Neutral', 'Bored', 'Neutral', 'Bored', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Bored', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Bored', 'Neutral', 'Bored', 'Neutral', 'Neutral', 'Sad', 'Neutral', 'Bored', 'Happy', 'Bored', 'Sad', 'Bored', 'Bored', 'Bored', 'HotAnger', 'HotAnger', 'HotAnger', 'Sad', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger']

trueDict["GG1"] = ['Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger']
predDict["GG1"] = ['Bored', 'Bored', 'Happy', 'Bored', 'Neutral', 'Sad', 'Bored', 'Happy', 'Happy', 'Happy', 'HotAnger', 'Happy', 'Bored', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Bored', 'Happy', 'Bored', 'Bored', 'Happy', 'Sad', 'Happy', 'Bored', 'Bored', 'Bored', 'Happy', 'Happy', 'HotAnger', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger']

trueDict["JG1"] = ['Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger']
predDict["JG1"] = ['Happy', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Bored', 'Sad', 'Happy', 'Sad', 'Sad', 'Neutral', 'Bored', 'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Sad', 'Sad', 'Happy', 'Happy', 'Happy', 'Bored', 'Sad', 'Bored', 'Sad', 'Happy', 'Bored', 'Happy', 'HotAnger', 'Happy', 'Sad', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'HotAnger', 'HotAnger', 'Happy', 'Happy', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'Happy', 'Happy']

trueDict["MF1"] = ['Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger']
predDict["MF1"] = ['Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Sad', 'Sad', 'Sad', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Happy', 'Bored', 'Bored', 'Bored', 'Bored', 'Neutral', 'Bored', 'HotAnger', 'Happy', 'HotAnger', 'HotAnger', 'HotAnger', 'Bored', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'Happy', 'HotAnger', 'HotAnger', 'Happy', 'HotAnger', 'HotAnger', 'HotAnger']

trueDict["MK1"] = ['Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger']
predDict["MK1"] = ['Bored', 'Bored', 'Bored', 'Happy', 'Sad', 'Sad', 'Bored', 'Sad', 'Sad', 'Sad', 'Bored', 'Sad', 'Happy', 'Happy', 'Happy', 'Bored', 'Happy', 'Bored', 'Happy', 'Bored', 'Bored', 'Happy', 'Happy', 'Bored', 'Sad', 'Happy', 'Happy', 'Happy', 'Happy', 'Bored', 'Bored', 'Happy', 'HotAnger', 'Happy', 'HotAnger', 'Happy', 'Happy', 'HotAnger', 'Happy', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'Happy', 'Happy', 'Happy', 'HotAnger', 'HotAnger']

trueDict["MM1"] = ['Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Bored', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger', 'HotAnger']
predDict["CM1"] = ['Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral', 'Neutral', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Happy', 'Happy', 'Sad', 'Sad', 'Bored', 'Happy', 'HotAnger', 'Happy', 'HotAnger', 'Sad', 'Sad', 'HotAnger', 'Happy', 'Sad', 'Happy', 'Happy', 'Happy', 'HotAnger', 'HotAnger', 'HotAnger', 'Sad', 'Happy', 'HotAnger', 'HotAnger', 'Happy', 'HotAnger', 'HotAnger']